### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by aashutoshrathi** [ltrc/kru2uni#1]
after  giving command `python .\krutidev2unicode.py -i input.txt -o output.txt`
It displays an error

> 
> File ".\krutidev2unicode.py", line 494
>     misplaced = re.compile(ur'[\u2014\u2013]')
>                                             ^
> SyntaxError: invalid syntax

**Comment by nehaljwani** [comment]
@aashutoshrathi This looks like a copy paste issue. The following worked for me:

```zsh
/tmp ❯❯❯ wget https://raw.githubusercontent.com/ltrc/kru2uni/master/krutidev2unicode.py
--2017-05-21 14:02:37--  https://raw.githubusercontent.com/ltrc/kru2uni/master/krutidev2unicode.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.48.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20051 (20K) [text/plain]
Saving to: ‘krutidev2unicode.py’

krutidev2unicode.py                                  100%[=====================================================================================================================>]  19.58K  65.8KB/s    in 0.3s    

2017-05-21 14:02:39 (65.8 KB/s) - ‘krutidev2unicode.py’ saved [20051/20051]

/tmp ❯❯❯ echo "esjk uke usgy gSA eS ,d Nk= gw¡A" | python krutidev2unicode.py
मेरा नाम नेहल है। मै एक छात्र हूँ।
```

**Comment by nehaljwani** [comment]
Re-open this issue if you feel otherwise. Also, please mention the platform (OSX, Linux, Windows) that you are trying to use this on.

**Comment by aashutoshrathi** [comment]
@nehaljwani I'm using it on powershell Windows 10, is there something else I should do ?

**Comment by nehaljwani** [comment]
@aashutoshrathi Are you using python3?

**Comment by aashutoshrathi** [comment]
Yes, precisely Python 3.6

**Comment by nehaljwani** [comment]
@aashutoshrathi Please try this https://github.com/ltrc/kru2uni/blob/python3/krutidev2unicode.py and provide feedback. It's experimental as of now.

**Comment by nehaljwani** [comment]
@aashutoshrathi Also, if it is possible for you to use `Python 2.7*`, please do that, as it is more tested.

**Comment by aashutoshrathi** [comment]
@nehaljwani getting this error on experimental 
> PS D:\Softwares\kru2uni-master> python .\krutidev2unicode.py -i input.txt -o output.txt
> Traceback (most recent call last):
>   File ".\krutidev2unicode.py", line 559, in <module>
>     args.output_file.write(kru2uni(line).decode('utf-8'))
>   File "C:\Users\Aashutosh Rathi\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>

**Comment by nehaljwani** [comment]
@aashutoshrathi Would it be possible to share your input file as an attachment here? That way I would be able to reproduce this error and provide a fix.

**Comment by aashutoshrathi** [comment]
[input.txt](http://textuploader.com/d9urn) This is input file

**Comment by nehaljwani** [comment]
@aashutoshrathi This is a Windows encoding issue which I am, for now, not able to reproduce on Linux. I have added a new commit. Download the newer version and try again.

**Comment by aashutoshrathi** [comment]
No newer version found, can you give me the link ? @nehaljwani

**Comment by nehaljwani** [comment]
@aashutoshrathi The link is the same. The file just got updated. Download it again from: https://raw.githubusercontent.com/ltrc/kru2uni/python3/krutidev2unicode.py

**Comment by aashutoshrathi** [comment]
@nehaljwani still getting error
`PS C:\Users\Aashutosh Rathi\Documents\Github\kru2uni> python krutidev2unicode.py -i input.txt -o output.txt
Traceback (most recent call last):
  File "krutidev2unicode.py", line 563, in <module>
    args.output_file.write(kru2uni(line))
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>`

**Comment by aashutoshrathi** [comment]
@nehaljwani I don't know where I'm getting wrong I even tried installing Python 2

**Comment by aashutoshrathi** [comment]
It worked 😄 
Thanks 🙇 This is really nice work.

**Comment by nehaljwani** [comment]
@aashutoshrathi Could you please share what changes you made to make it work? Did you make the Python3 version work or the Python2?
