### ISSUE TITLE
Error while printing in Bash

### ISSUE THREAD

**Issue by aashutoshrathi** [ltrc/kru2uni#2]
As you mentioned in README.md, this `$ echo "esjk uke usgy gSA eS ,d Nk= gw¡A" | python krutidev2unicode.py ` should print output in console.
and this is working but for all those text which contains `ष` as this is mapped to `"` in KrutiDev so whenever we write `$ echo "vk'kqrks"k jkBh" | python krutidev2unicode.py `
It should print `आशुतोष राठी` but instead it will not work as there are multiple `"`.
Anything you can do to fix it?

**Comment by aashutoshrathi** [comment]
@nehaljwani Take a look at this one.

**Comment by nehaljwani** [comment]
@aashutoshrathi You need to escape the quote. Try this:
```
$ echo "vk'kqrks\"k jkBh" | python krutidev2unicode.py                                                                                                                                                    
आशुतोष राठी
```
